export const mapiconData = [
  {
    id: 1,
    name: "城跡",
    nameKana: "じょうせき",
    difficulty: "easy",
    image: "img/mapicon/joseki.svg",
  },
  {
    id: 2,
    name: "風車",
    nameKana: "ふうしゃ",
    difficulty: "easy",
    image: "img/mapicon/fusha.svg",
  },
  {
    id: 3,
    name: "ヤシ科樹木",
    nameKana: "ヤシかじゅもく",
    difficulty: "easy",
    image: "img/mapicon/yashikajumoku.svg",
  },
  {
    id: 4,
    name: "竹林",
    nameKana: "ちくりん",
    difficulty: "easy",
    image: "img/mapicon/chikurin.svg",
  },
  {
    id: 5,
    name: "針葉樹林",
    nameKana: "しんようじゅりん",
    difficulty: "easy",
    image: "img/mapicon/shinyojurin.svg",
  },
  {
    id: 6,
    name: "荒地",
    nameKana: "あれち",
    difficulty: "easy",
    image: "img/mapicon/arechi.svg",
  },
  {
    id: 7,
    name: "広葉樹林",
    nameKana: "こうようじゅりん",
    difficulty: "easy",
    image: "img/mapicon/koyojurin.svg",
  },
  {
    id: 8,
    name: "桑畑",
    nameKana: "くわはた",
    difficulty: "easy",
    image: "img/mapicon/kuwahata.svg",
  },
  {
    id: 9,
    name: "畑",
    nameKana: "はたけ",
    difficulty: "easy",
    image: "img/mapicon/hatake.svg",
  },
  {
    id: 10,
    name: "茶畑",
    nameKana: "ちゃばたけ",
    difficulty: "easy",
    image: "img/mapicon/chabatake.svg",
  },
  {
    id: 11,
    name: "果樹園",
    nameKana: "かじゅえん",
    difficulty: "easy",
    image: "img/mapicon/kajuen.svg",
  },
  {
    id: 12,
    name: "田",
    nameKana: "た",
    difficulty: "easy",
    image: "img/mapicon/ta.svg",
  },
  {
    id: 13,
    name: "灯台",
    nameKana: "とうだい",
    difficulty: "easy",
    image: "img/mapicon/todai.svg",
  },
  {
    id: 14,
    name: "温泉",
    nameKana: "おんせん",
    difficulty: "easy",
    image: "img/mapicon/onsen.svg",
  },
  {
    id: 15,
    name: "史跡・名勝・天然記念物",
    nameKana: "しせき・めいしょう・てんねんきねんぶつ",
    difficulty: "easy",
    image: "img/mapicon/shiseki.svg",
  },
  {
    id: 16,
    name: "煙突",
    nameKana: "えんとつ",
    difficulty: "easy",
    image: "img/mapicon/entotsu.svg",
  },
  {
    id: 17,
    name: "老人ホーム",
    nameKana: "ろうじんホーム",
    difficulty: "easy",
    image: "img/mapicon/rojin.svg",
  },
  {
    id: 18,
    name: "工場",
    nameKana: "こうじょう",
    difficulty: "easy",
    image: "img/mapicon/kojo.svg",
  },
  {
    id: 19,
    name: "発電所",
    nameKana: "はつでんしょ",
    difficulty: "easy",
    image: "img/mapicon/hatsudensho.svg",
  },
  {
    id: 20,
    name: "図書館",
    nameKana: "としょかん",
    difficulty: "easy",
    image: "img/mapicon/toshokan.svg",
  },
  {
    id: 21,
    name: "博物館",
    nameKana: "はくぶつかん",
    difficulty: "easy",
    image: "img/mapicon/hakubutsukan.svg",
  },
  {
    id: 22,
    name: "寺院",
    nameKana: "じいん",
    difficulty: "easy",
    image: "img/mapicon/jiin.svg",
  },
  {
    id: 23,
    name: "神社",
    nameKana: "じんじゃ",
    difficulty: "easy",
    image: "img/mapicon/jinja.svg",
  },
  {
    id: 24,
    name: "病院",
    nameKana: "びょういん",
    difficulty: "easy",
    image: "img/mapicon/byoin.svg",
  },
  {
    id: 25,
    name: "高等学校",
    nameKana: "こうとうがっこう",
    difficulty: "easy",
    image: "img/mapicon/koko.svg",
  },
  {
    id: 26,
    name: "小中学校",
    nameKana: "ちょうちゅうがっこう",
    difficulty: "easy",
    image: "img/mapicon/shochugakko.svg",
  },
  {
    id: 27,
    name: "郵便局",
    nameKana: "ゆうびんきょく",
    difficulty: "easy",
    image: "img/mapicon/yubinkyoku.svg",
  },
  {
    id: 28,
    name: "交番",
    nameKana: "こうばん",
    difficulty: "easy",
    image: "img/mapicon/koban.svg",
  },
  {
    id: 29,
    name: "警察署",
    nameKana: "けいさつしょ",
    difficulty: "easy",
    image: "img/mapicon/kesatsusho.svg",
  },
  {
    id: 30,
    name: "消防署",
    nameKana: "しょうぼうしょ",
    difficulty: "easy",
    image: "img/mapicon/shobosho.svg",
  },
  {
    id: 31,
    name: "税務署",
    nameKana: "ぜいむしょ",
    difficulty: "easy",
    image: "img/mapicon/zemusho.svg",
  },
  {
    id: 32,
    name: "裁判所",
    nameKana: "さいばんしょ",
    difficulty: "easy",
    image: "img/mapicon/saibansho.svg",
  },
  {
    id: 33,
    name: "官公署",
    nameKana: "かんこうしょ",
    difficulty: "easy",
    image: "img/mapicon/kankosho.svg",
  },
  {
    id: 34,
    name: "町役場",
    nameKana: "まちやくば",
    difficulty: "easy",
    image: "img/mapicon/machiyakuba.svg",
  },
  {
    id: 35,
    name: "市役所",
    nameKana: "しやくしょ",
    difficulty: "easy",
    image: "img/mapicon/siyakusho.svg",
  },
  {
    id: 36,
    name: "重要港",
    nameKana: "じゅうようこう",
    difficulty: "difficult",
    image: "img/mapicon/juyoko.svg",
  },
  {
    id: 37,
    name: "採鉱地",
    nameKana: "さいこうち",
    difficulty: "difficult",
    image: "img/mapicon/saikochi.svg",
  },
  {
    id: 38,
    name: "噴火口・噴気口",
    nameKana: "ふんかこう・ふんきこう",
    difficulty: "difficult",
    image: "img/mapicon/funkako.svg",
  },
  {
    id: 39,
    name: "坑口",
    nameKana: "こうこう",
    difficulty: "difficult",
    image: "img/mapicon/kodoiriguchi.svg",
  },
  {
    id: 40,
    name: "笹地",
    nameKana: "ささち",
    difficulty: "difficult",
    image: "img/mapicon/sasachi.svg",
  },
  {
    id: 41,
    name: "ハイマツ地",
    nameKana: "ハイマツち",
    difficulty: "difficult",
    image: "img/mapicon/haimatsu.svg",
  },
  {
    id: 42,
    name: "採石地",
    nameKana: "さいせきち",
    difficulty: "difficult",
    image: "img/mapicon/saisekichi.svg",
  },
  {
    id: 43,
    name: "港湾",
    nameKana: "こうわん",
    difficulty: "difficult",
    image: "img/mapicon/kowan.svg",
  },
  {
    id: 44,
    name: "漁港",
    nameKana: "ぎょこう",
    difficulty: "difficult",
    image: "img/mapicon/gyoko.svg",
  },
  {
    id: 45,
    name: "電波塔",
    nameKana: "でんぱとう",
    difficulty: "difficult",
    image: "img/mapicon/denpato.svg",
  },
  {
    id: 46,
    name: "記念碑",
    nameKana: "きねんひ",
    difficulty: "difficult",
    image: "img/mapicon/kinenhi.svg",
  },
  {
    id: 47,
    name: "自衛隊",
    nameKana: "じえいたい",
    difficulty: "difficult",
    image: "img/mapicon/jietai.svg",
  },
  {
    id: 48,
    name: "電報・電話局",
    nameKana: "でんぽう・でんわきょく",
    difficulty: "difficult",
    image: "img/mapicon/denpo.svg",
  },
  {
    id: 49,
    name: "材料置場",
    nameKana: "ざいりょうおきば",
    difficulty: "difficult",
    image: "img/mapicon/zairyo.svg",
  },
  {
    id: 50,
    name: "検察庁",
    nameKana: "けんさつちょう",
    difficulty: "difficult",
    image: "img/mapicon/kensatsucho.svg",
  },
  {
    id: 51,
    name: "鳥居",
    nameKana: "とりい",
    difficulty: "difficult",
    image: "img/mapicon/tori.svg",
  },
  {
    id: 52,
    name: "起重機",
    nameKana: "きじゅうき",
    difficulty: "difficult",
    image: "img/mapicon/kijuki.svg",
  },
  {
    id: 53,
    name: "立像",
    nameKana: "りつぞう",
    difficulty: "difficult",
    image: "img/mapicon/ritsuzo.svg",
  },
  {
    id: 54,
    name: "墓地",
    nameKana: "ぼち",
    difficulty: "difficult",
    image: "img/mapicon/bochi.svg",
  },
  {
    id: 55,
    name: "倉庫",
    nameKana: "そうこ",
    difficulty: "difficult",
    image: "img/mapicon/soko.svg",
  },
  {
    id: 56,
    name: "銀行",
    nameKana: "ぎんこう",
    difficulty: "difficult",
    image: "img/mapicon/ginko.svg",
  },
  {
    id: 57,
    name: "油井・ガス井",
    nameKana: "ゆせい・ガスせい",
    difficulty: "difficult",
    image: "img/mapicon/yuse.svg",
  },
  {
    id: 58,
    name: "高塔",
    nameKana: "こうとうがっこう",
    difficulty: "difficult",
    image: "img/mapicon/koto.svg",
  },
  {
    id: 59,
    name: "渡船（フェリー）",
    nameKana: "とせん（フェリー）",
    difficulty: "difficult",
    image: "img/mapicon/ferry.svg",
  },
  {
    id: 60,
    name: "渡船（その他の旅客船）",
    nameKana: "とせん（そのたのりょかくせん）",
    difficulty: "difficult",
    image: "img/mapicon/ryokakusen.svg",
  },
  {
    id: 61,
    name: "水準点",
    nameKana: "すいじゅんてん",
    difficulty: "difficult",
    image: "img/mapicon/suijunten.svg",
  },
  {
    id: 62,
    name: "電子基準点",
    nameKana: "でんしきじゅんてん",
    difficulty: "difficult",
    image: "img/mapicon/denshikijunten.svg",
  },
  {
    id: 63,
    name: "三角点",
    nameKana: "さんかくてん",
    difficulty: "difficult",
    image: "img/mapicon/sankakuten.svg",
  },
  {
    id: 64,
    name: "高等専門学校",
    nameKana: "こうとうせんもんがっこう",
    difficulty: "difficult",
    image: "img/mapicon/kosen.svg",
  },
  {
    id: 65,
    name: "短期大学",
    nameKana: "たんきだいがく",
    difficulty: "difficult",
    image: "img/mapicon/tandai.svg",
  },
  {
    id: 66,
    name: "大学",
    nameKana: "だいがく",
    difficulty: "difficult",
    image: "img/mapicon/daigaku.svg",
  },
  {
    id: 67,
    name: "保健所",
    nameKana: "ほけんじょ",
    difficulty: "difficult",
    image: "img/mapicon/hokenjo.svg",
  },
  {
    id: 68,
    name: "気象台",
    nameKana: "きしょうだい",
    difficulty: "difficult",
    image: "img/mapicon/kishodai.svg",
  },
  {
    id: 69,
    name: "森林管理署",
    nameKana: "しんいんかんりしょ",
    difficulty: "difficult",
    image: "img/mapicon/shinrin.svg",
  },
];
